apiVersion: v2
name: mail-relay
description: Haraka-based SMTP relay with DKIM signing and DNS automation
type: application
version: 3.4.13
appVersion: "3.4.13"
keywords:
  - smtp
  - mail
  - relay
  - haraka
  - dkim
  - kubernetes
home: https://github.com/lnking81/mail-relay-chart
sources:
  - https://github.com/lnking81/mail-relay-chart
  - https://github.com/haraka/Haraka
maintainers:
  - name: lnking81
