{{- if and .Values.tls.enabled .Values.tls.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "mail-relay.fullname" . }}-tls
  labels:
    {{- include "mail-relay.labels" . | nindent 4 }}
spec:
  secretName: {{ include "mail-relay.fullname" . }}-tls
  dnsNames:
    - {{ .Values.mail.hostname }}
    {{- range .Values.tls.certManager.additionalDnsNames }}
    - {{ . }}
    {{- end }}
  issuerRef:
    name: {{ .Values.tls.certManager.issuerRef.name }}
    kind: {{ .Values.tls.certManager.issuerRef.kind }}
    {{- if .Values.tls.certManager.issuerRef.group }}
    group: {{ .Values.tls.certManager.issuerRef.group }}
    {{- end }}
  {{- if .Values.tls.certManager.duration }}
  duration: {{ .Values.tls.certManager.duration }}
  {{- end }}
  {{- if .Values.tls.certManager.renewBefore }}
  renewBefore: {{ .Values.tls.certManager.renewBefore }}
  {{- end }}
  privateKey:
    algorithm: {{ .Values.tls.certManager.privateKey.algorithm }}
    size: {{ .Values.tls.certManager.privateKey.size }}
{{- end }}
