{{/* Hetzner Cloud Secret */}}
{{- if and .Values.dns.enabled .Values.dns.ptr.enabled (or (eq .Values.dns.ptr.provider "hetzner") (eq .Values.dns.ptr.provider "hetzner-cloud")) (not .Values.dns.hetzner.existingSecret) .Values.dns.hetzner.apiToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mail-relay.fullname" . }}-hetzner
  labels:
    {{- include "mail-relay.labels" . | nindent 4 }}
type: Opaque
data:
  api-token: {{ .Values.dns.hetzner.apiToken | b64enc | quote }}
{{- end }}
---
{{/* Hetzner Robot Secret (Dedicated Servers) */}}
{{- if and .Values.dns.enabled .Values.dns.ptr.enabled (eq .Values.dns.ptr.provider "hetzner-robot") (not .Values.dns.hetznerRobot.existingSecret) .Values.dns.hetznerRobot.username .Values.dns.hetznerRobot.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mail-relay.fullname" . }}-hetzner-robot
  labels:
    {{- include "mail-relay.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.dns.hetznerRobot.username | b64enc | quote }}
  password: {{ .Values.dns.hetznerRobot.password | b64enc | quote }}
{{- end }}
